//ARQUIVO PARA FAZER REQUISIÇÕES HTTP
//----------------------------------------------------------------------------------------------------------------------
//Usuario REQUESTS
//Criar Usuario
POST http://localhost:3333/adicionarUsuario
content-type: application/json

    {
        "login": "UsuarioTeste",
        "password": "Senh@Teste258456"
    }

###

//Listar todos os usuarios
GET http://localhost:3333/listarUsuarios

###

//Listar um usuario
GET http://localhost:3333/listarUsuario/1

###
//Editar Usuario
PUT http://localhost:3333/editarUsuario/1
content-type: application/json

    {
        "login": "UsuarioParaTeste",
        "password": "Senh@Teste258456"
    }

###
//Deletar Usuario
DELETE http://localhost:3333/deletarUsuario/1

###
//Listar o login do usuario e todos os seus contatos - ASSOCIACAO N-N
GET http://localhost:3333/listarUsuarioContatos/1

###

//-----------------------------------------------------------------------------
//Contato REQUESTS
//Criar Contato
POST http://localhost:3333/adicionarContato
content-type: application/json

{
    "name" : "Nome do contato 1",
    "email" : "contato1@teste.com.br",
    "phone_number" : "1236987414",
    "image_url" : "./images"
}

###

//Listar todos os contatos
GET http://localhost:3333/listarContatos

###

//Listar contato pelo id, passando o numero de id como parametro na url.
GET http://localhost:3333/listarContato/1

###

//Alterar contato pelo id, passando o numero de id como parametro na url.
PUT http://localhost:3333/alterarContato/1
content-type: application/json

{
    "name" : "Nome do contato 1",
    "email" : "contato1@teste.com.br",
    "phone_number" : "1236987414",
    "image_url" : "./images"
}

###

//Deletar contato pelo id, passando o numero de id como parametro na url.
DELETE http://localhost:3333/deletarContato/2
