//Criar Usuario
POST http://localhost:3333/adicionarUsuario
content-type: application/json

    {
        "login": "soldier",
        "password": "666"
    }

###

//Listar todos os usuarios
GET http://localhost:3333/listarUsuarios

###

//Criar Contato
POST http://localhost:3333/adicionarContato
content-type: application/json

{
    "name" : "Rafael",
    "email" : "rafael@teste.com.br",
    "phone_number" : "1236987414",
    "image_url" : "./images"
}

###

//Listar todos os contatos
GET http://localhost:3333/listarContatos

###

//Listar contato pelo id, passando o numero de id como parametro na url.
GET http://localhost:3333/listarContato/5

###

//Alterar contato pelo id, passando o numero de id como parametro na url.
PUT http://localhost:3333/alterarContato/1
content-type: application/json

{
    "name" : "Gabriel",
    "email" : "Rodrigo@teste.com.br",
    "phone_number" : "66668888552",
    "image_url" : "./images"
}

###

//Deletar contato pelo id, passando o numero de id como parametro na url.
DELETE http://localhost:3333/deletarContato/2

###

//Listar o login do usuario e todos os seus contatos - ASSOCIACAO N-N
GET http://localhost:3333/listarUsuarioContatos/1